services:
  pgsql:
    image: postgres:15-alpine
    container_name: job-board-pg
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: job_board
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d job_board']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  data:
